name: ci

on:
  push:
    branches: [main]
    paths:
      - 'public/**'
      - 'src/**'
      - '*.json'
      - 'bun.lockb'
      - '*.config.{js,ts}'
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  lint:
    name: Check for build and type issues
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "blog"
          directory: "dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
