name: ci

on:
  push:
    branches: [main]
    paths:
      - 'public/**'
      - 'src/**'
      - '*.json'
      - 'bun.lockb'
      - '*.config.{js,ts}'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "blog"
          directory: "dist"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: "3"
